# file = open('sample.txt', 'x')
# file.write("Hello world!")
# file.close()
# file = open('sample.txt', 'r')
# text = file.read()
# print(text)
# file.close()
#file = open('folder/test.txt', 'r')
# text = file.read()
# print(text)
# file = open('test.txt', 'a')
# #
# file.write(' world!')
# file.close()
# print("Файл успешно записан!")